# Generated by Django 3.1.6 on 2021-02-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtocategory',
            fields=[
                ('pk_category', models.AutoField(db_column='PK_Category', primary_key=True, serialize=False)),
                ('namecategory', models.CharField(db_column='nameCategory', max_length=200)),
            ],
            options={
                'db_table': 'AvtoCategory',
            },
        ),
        migrations.CreateModel(
            name='Avtofirm',
            fields=[
                ('pk_avtofirm', models.AutoField(db_column='PK_AvtoFirm', primary_key=True, serialize=False)),
                ('firmname', models.CharField(db_column='firmName', max_length=100)),
            ],
            options={
                'db_table': 'AvtoFirm',
            },
        ),
        migrations.CreateModel(
            name='Baseavto',
            fields=[
                ('pk_baseavto', models.AutoField(db_column='PK_BaseAvto', primary_key=True, serialize=False)),
                ('modelname', models.CharField(db_column='modelName', max_length=200)),
                ('pk_avtofirm', models.ForeignKey(blank=True, db_column='PK_AvtoFirm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.avtofirm')),
            ],
            options={
                'db_table': 'BaseAvto',
            },
        ),
        migrations.CreateModel(
            name='Superstructure',
            fields=[
                ('pk_superstructure', models.AutoField(db_column='PK_Superstructure', primary_key=True, serialize=False)),
                ('supestructurename', models.CharField(db_column='supestructureName', max_length=200)),
            ],
            options={
                'db_table': 'Superstructure',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('pk_car', models.AutoField(db_column='PK_Car', primary_key=True, serialize=False)),
                ('yearissue', models.DateField(blank=True, db_column='yearIssue', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('imagepath', models.CharField(blank=True, db_column='imagePath', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pk_baseavto', models.ForeignKey(db_column='PK_BaseAvto', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.baseavto')),
                ('pk_category', models.ForeignKey(blank=True, db_column='PK_Category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.avtocategory')),
                ('pk_superstructure', models.ForeignKey(db_column='PK_Superstructure', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.superstructure')),
            ],
            options={
                'db_table': 'Car',
            },
        ),
    ]
